name: electron-build

on: 
  push:
    branches: 
      - harsom

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
#       - name: npm install, build
#         run: npm install && npm run electron:build --linux deb tar.xz
#         env:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy # 发布
        env:
          GH_REF: github.com/roy-lau/nodejs.git # GitHub 仓库 SSH 地址
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 预先生成 GitHub Token
        run: |
          git clone https://$GH_REF --depth=1 -b harsom .deploy_git
          cd .deploy_git
          git checkout -b deploy
          npm install && npm run electron:build --linux deb tar.xz # 运行安装 和 打包脚本
          git config --global user.name "roy-lau"
          git config --global user.email "roylau_vip@163.com"
          git add .
          git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
          git remote set-url origin https://roy-lau:3f6721cf0a74c9a335677cfbbb415d4b543da017@$GH_REF
          git push --set-upstream origin deploy
