name: electron-build

on: 
  push:
    branches: 
      - harsom

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
        
      - name: npm install, build
        uses: actions/checkout@build
        with:
          fetch-depth: 1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: dist_electron
          BUILD_SCRIPT: npm install && npm run electron:build --linux deb tar.xz
